application: py2lunch
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup|start|stop).*
  script: project.wsgi.application
  login: admin
  secure: always

- url: /_ah/internalupload.*
  script: project.wsgi.application
  secure: always

- url: /static
  static_dir: static/
  secure: always

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: project.wsgi.application
  secure: always
  login: admin

- url: /.*
  script: project.wsgi.application
  secure: always

env_variables:
  PYTHONHTTPSVERIFY: 1

skip_files:
  - ^manage\.py$
  - ^README\.md$
  - ^install_deps$
  - ^requirements/.*\.txt$
  - ^sitepackages/dev.*
  - ^.*\.(egg|dist)-info/.*$

  # Defaults.
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
